# CONFIGURACIÓN DE CONEXIÓN A ORACLE CLOUD
spring.datasource.url=jdbc:oracle:thin:@learningplatformvalidationdb_low?TNS_ADMIN=/app/wallet

spring.datasource.username=ADMIN
spring.datasource.password=LearningPlatformSumativa3
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# CONFIGURACIÓN JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CONFIGURACIÓN AWS S3 
spring.cloud.aws.s3.bucket=plataforma-inscripciones-caceres-2026
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
spring.cloud.aws.credentials.session-token=${AWS_SESSION_TOKEN}