# CONFIGURACIÓN DE CONEXIÓN A ORACLE CLOUD
# Nombre de la base de datos, wallet, usuario, contraseña y driver
spring.datasource.url=jdbc:oracle:thin:@learningplatformvalidationdb_low?TNS_ADMIN=C:/oracle_wallet


spring.datasource.username=ADMIN
spring.datasource.password=LearningPlatformSumativa3

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# CONFIGURACIÓN JPA / HIBERNATE

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
oracle.net.ssl_server_dn_match=true
oracle.net.ssl_version=1.2

# CONFIGURACIÓN AWS S3
spring.cloud.aws.s3.bucket=plataforma-inscripciones-caceres-2026
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=${ASIAX4UJUVZVX4HTGPYF}
spring.cloud.aws.credentials.secret-key=${Q58GzZgGQ6lVBYXyOwj2OlT7wuyikImBUcEjnRLp}
spring.cloud.aws.credentials.session-token=${IQoJb3JpZ2luX2VjEDcaCXVzLXdlc3QtMiJIMEYCIQDMLaOTWMF2nbBmOKyVaGObIEIsYHsEK7VJWsr3bv9zcgIhAIoWTmgPtWV7odVCGc3KvJof+ek8EHmxC64+ISbyLGwyKq8CCAAQARoMNTQyNTI4Mjg2MzE1Igw4leUeMs5XV758qiQqjAKPPgt3jzt5HNDfA/H74BsJoh6rADpseqnCvWN8iW3yprc6vtN8ngw2+Df8x1XbH4/i3bYl6AEVBi0yb79AglURQFGHey/+vnpwq7rocW9j1pAP1BqqNpeCa2+uGWT706jqxu1fV1BUG0clmzB4mTiIokeTm0Uu7tpSYcqGWTJynmw05/csATLCfiHBKRaQGLufFfisLR+uFIz7aXhry8lue/9qiJNQz5WfcNc+sCI+kJVUiaJD3Tl4pbdsBOJ5Hbgs8px9AOkJtsrZ5BFXq+NXoHpra+pnE3OuIUX48im2hnQw37G9lprulcecEiHD4/B0NAiwaW8MdPgzwxCUotIdtcLdcIhSYNAeugN1MICD89AGOpwBhqF0r88DvOE+4zgl9CeFkyMFlNLnyNJs0OZZ3D76SxSSGKMMAcP4LukoXGPoUKslbAvR9tUP06R+ofAwFH6qnKQuzYlGwZWYa6urG3GHRpxeHGydEtAS7NG2F+WPmY9+wPUc3ozddrJG0sXfFSKG+CEaMgBQFOxuQvBmr1APMEPiKVGJ0zyGZu6XhLFQhdw2vFGA59c1RER4JJeoDOCKERHUB_TOKEN}